tournament_name = "Big Funny Cup IV: Suomi Edition"
season_num = 1
date = 2024-01-06
has_losers = true
playoff_teams = 10

###################### WINNERS ######################

#1
[[brackets.winners]]
team1 = "Moai"
score1 = 2
team2 = "Gambit"
score2 = 1

#2
[[brackets.winners]]
team1 = "Big Funky"
score1 = 3
team2 = "Vidya"
score2 = 1

#3
[[brackets.winners]]
team1 = "Bone Zone"
score1 = 2
team2 = "Moai"
score2 = 0

#4
[[brackets.winners]]
team1 = "Cartoons FC"
score1 = 0
team2 = "Alpha Space Bros"
score2 = 2

#5
[[brackets.winners]]
team1 = "Nintendont"
score1 = 2
team2 = "Disney"
score2 = 0

#6
[[brackets.winners]]
team1 = "Big Funky"
score1 = 2
team2 = "The Dump"
score2 = 1

#9
[[brackets.winners]]
team1 = "Bone Zone"
score1 = 0
team2 = "Alpha Space Bros"
score2 = 1

#10
[[brackets.winners]]
team1 = "Nintendont"
score1 = 2
team2 = "Big Funky"
score2 = 1

#15
[[brackets.winners]]
team1 = "Alpha Space Bros"
score1 = 0
team2 = "Nintendont"
score2 = 1


#################### GRAND FINAL ####################

#18
[[grand_final]]
team1 = "Nintendont"
score1 = 5
team2 = "Alpha Space Bros"
score2 = 0

###################### LOSERS #######################

#7
[[brackets.losers]]
team1 = "The Dump"
score1 = 0
team2 = "Gambit"
score2 = 3

#8
[[brackets.losers]]
team1 = "Moai"
score1 = 0
team2 = "Vidya"
score2 = 1

#11
[[brackets.losers]]
team1 = "Disney"
score1 = 0
team2 = "Gambit"
score2 = 3

#12
[[brackets.losers]]
team1 = "Cartoons FC"
score1 = 2
team2 = "Vidya"
score2 = 0

#13
[[brackets.losers]]
team1 = "Bone Zone"
score1 = 0
team2 = "Gambit"
score2 = 3

#14
[[brackets.losers]]
team1 = "Big Funky"
score1 = 2
team2 = "Cartoons FC"
score2 = 3

#16
[[brackets.losers]]
team1 = "Gambit"
score1 = 0
team2 = "Cartoons FC"
score2 = 1

#17
[[brackets.losers]]
team1 = "Alpha Space Bros"
score1 = 3
team2 = "Cartoons FC"
score2 = 1
