tournament_name = "Big Funny Cup I"
season_num = 1
date = 2023-07-01
has_losers = true
playoff_teams = 8

###################### WINNERS ######################

#1
[[brackets.winners]]
team1 = "Alpha Space Bros"
score1 = 1
team2 = "Nintendont"
score2 = 0

#2
[[brackets.winners]]
team1 = "Big Funky"
score1 = 0
team2 = "Bone Zone"
score2 = 1

#3
[[brackets.winners]]
team1 = "Moai"
score1 = 2
team2 = "Disney"
score2 = 5

#4
[[brackets.winners]]
team1 = "The Dump"
score1 = 0
team2 = "Cartoons FC"
score2 = 4

#7
[[brackets.winners]]
team1 = "Alpha Space Bros"
score1 = 0
team2 = "Bone Zone"
score2 = 1

#8
[[brackets.winners]]
team1 = "Disney"
score1 = 0
team2 = "Cartoons FC"
score2 = 1

#11
[[brackets.winners]]
team1 = "Bone Zone"
score1 = 2
team2 = "Cartoons FC"
score2 = 0

#################### GRAND FINAL ####################

#14
[[grand_final]]
team1 = "Bone Zone"
score1 = 2
pen1 = 2
team2 = "Nintendont"
score2 = 2
pen2 = 4

#15
[[grand_final]]
team1 = "Bone Zone"
score1 = 0
team2 = "Nintendont"
score2 = 1

###################### LOSERS #######################

#5
[[brackets.losers]]
team1 = "Nintendont"
score1 = 3
team2 = "Big Funky"
score2 = 2

#6
[[brackets.losers]]
team1 = "Moai"
score1 = 1
team2 = "The Dump"
score2 = 3

#9
[[brackets.losers]]
team1 = "Disney"
score1 = 1
team2 = "Nintendont"
score2 = 2

#10
[[brackets.losers]]
team1 = "Alpha Space Bros"
score1 = 1
team2 = "The Dump"
score2 = 4

#12
[[brackets.losers]]
team1 = "Nintendont"
score1 = 1
team2 = "The Dump"
score2 = 0

#13
[[brackets.losers]]
team1 = "Cartoons FC"
score1 = 3
team2 = "Nintendont"
score2 = 4
