tournament_name = "Big Funny Cup V: Breaking News Edition"
season_num = 2
date = 2024-03-02
has_losers = false
playoff_teams = 8

####################### GROUP A #######################

#1
[[brackets.groups]]
group_id = "A"
team1 = "Nintendont"
score1 = 3
team2 = "Cartoons FC"
score2 = 3

#2
[[brackets.groups]]
group_id = "A"
team1 = "Disney"
score1 = 2
team2 = "Alpha Space Bros"
score2 = 1

#3
[[brackets.groups]]
group_id = "A"
team1 = "Nintendont"
score1 = 0
team2 = "Disney"
score2 = 2

#4
[[brackets.groups]]
group_id = "A"
team1 = "Cartoons FC"
score1 = 4
team2 = "Alpha Space Bros"
score2 = 0

#5
[[brackets.groups]]
group_id = "A"
team1 = "Nintendont"
score1 = 2
team2 = "Alpha Space Bros"
score2 = 1

#6
[[brackets.groups]]
group_id = "A"
team1 = "Cartoons FC"
score1 = 1
team2 = "Disney"
score2 = 2


####################### GROUP B #######################

#1
[[brackets.groups]]
group_id = "B"
team1 = "Moai"
score1 = 0
team2 = "The Dump"
score2 = 1

#2
[[brackets.groups]]
group_id = "B"
team1 = "HmX Gaming"
score1 = 1
team2 = "Vidya"
score2 = 0

#3
[[brackets.groups]]
group_id = "B"
team1 = "Moai"
score1 = 2
team2 = "HmX Gaming"
score2 = 1

#4
[[brackets.groups]]
group_id = "B"
team1 = "The Dump"
score1 = 0
team2 = "Vidya"
score2 = 2

#5
[[brackets.groups]]
group_id = "B"
team1 = "Moai"
score1 = 1
team2 = "Vidya"
score2 = 1

#6
[[brackets.groups]]
group_id = "B"
team1 = "The Dump"
score1 = 0
team2 = "HmX Gaming"
score2 = 1


####################### GROUP C #######################

#1
[[brackets.groups]]
group_id = "C"
team1 = "Autoism"
score1 = 0
team2 = "Big Funky"
score2 = 1

#2
[[brackets.groups]]
group_id = "C"
team1 = "Bone Zone"
score1 = 0
team2 = "Gambit"
score2 = 2

#3
[[brackets.groups]]
group_id = "C"
team1 = "Autoism"
score1 = 2
team2 = "Bone Zone"
score2 = 0

#4
[[brackets.groups]]
group_id = "C"
team1 = "Big Funky"
score1 = 0
team2 = "Gambit"
score2 = 3

#5
[[brackets.groups]]
group_id = "C"
team1 = "Autoism"
score1 = 3
team2 = "Gambit"
score2 = 0

#6
[[brackets.groups]]
group_id = "C"
team1 = "Big Funky"
score1 = 1
team2 = "Bone Zone"
score2 = 0


###################### WINNERS ######################

#1
[[brackets.winners]]
team1 = "Disney"
score1 = 3
team2 = "Moai"
score2 = 1

#2
[[brackets.winners]]
team1 = "Vidya"
score1 = 1
team2 = "Gambit"
score2 = 2

#3
[[brackets.winners]]
team1 = "Autoism"
score1 = 1
team2 = "Cartoons FC"
score2 = 5

#4
[[brackets.winners]]
team1 = "Big Funky"
score1 = 2
pen1 = 3
team2 = "HmX Gaming"
score2 = 2
pen2 = 1

#5
[[brackets.winners]]
team1 = "Disney"
score1 = 1
team2 = "Gambit"
score2 = 0

#6
[[brackets.winners]]
team1 = "Cartoons FC"
score1 = 3
team2 = "Big Funky"
score2 = 2

#7 – FINAL
[[brackets.winners]]
team1 = "Disney"
score1 = 2
team2 = "Cartoons FC"
score2 = 0