tournament_name = "Big Funny Cup XI: Clickbait Edition"
season_num = 4
date = 2026-06-18
has_losers = true
playoff_teams = 16
point_system = "LinearV1"

##################### HEAD TO HEAD ####################

###################### WINNERS ######################

#1
[[brackets.winners]]
team1 = "HmX Gaming"
score1 = 1
team2 = "Cartoons FC"
score2 = 2

#2
[[brackets.winners]]
team1 = "FC Fine Dining"
score1 = 1
team2 = "Cursed"
score2 = 3

#3
[[brackets.winners]]
team1 = "FC PC"
score1 = 0
team2 = "Alpha Space Bros"
score2 = 2

#4
[[brackets.winners]]
team1 = "Gambit"
score1 = 3
team2 = "Vidya"
score2 = 2

#5
[[brackets.winners]]
team1 = "Disney"
score1 = 3
team2 = "Nintendont"
score2 = 1

#6
[[brackets.winners]]
team1 = "Bone Zone"
score1 = 2
team2 = "Funny Fauna"
score2 = 1

#7
[[brackets.winners]]
team1 = "Legoland"
score1 = 1
team2 = "Autoism"
score2 = 0

#8
[[brackets.winners]]
team1 = "Big Funky"
score1 = 4
team2 = "Moai"
score2 = 0

#13
[[brackets.winners]]
team1 = "Cartoons FC"
score1 = 1
team2 = "Cursed"
score2 = 3

#14
[[brackets.winners]]
team1 = "Alpha Space Bros"
score1 = 5
team2 = "Gambit"
score2 = 0

#15
[[brackets.winners]]
team1 = "Disney"
score1 = 3
team2 = "Bone Zone"
score2 = 2

#16
[[brackets.winners]]
team1 = "Legoland"
score1 = 0
pen1 = 1
team2 = "Big Funky"
score2 = 0
pen2 = 3

#21
[[brackets.winners]]
team1 = "Cursed"
score1 = 3
team2 = "Alpha Space Bros"
score2 = 4

#22
[[brackets.winners]]
team1 = "Disney"
score1 = 3
team2 = "Big Funky"
score2 = 1

#27
[[brackets.winners]]
team1 = "Alpha Space Bros"
score1 = 0
team2 = "Disney"
score2 = 3

#################### GRAND FINAL ####################

#30
[[grand_final]]
team1 = "Disney"
score1 = 1
team2 = "Cartoons FC"
score2 = 2

#31
[[grand_final]]
team1 = "Disney"
score1 = 0
team2 = "Cartoons FC"
score2 = 1

###################### LOSERS #######################

#9
[[brackets.losers]]
team1 = "HmX Gaming"
score1 = 1
team2 = "FC Fine Dining"
score2 = 2

#10
[[brackets.losers]]
team1 = "FC PC"
score1 = 0
team2 = "Vidya"
score2 = 1

#11
[[brackets.losers]]
team1 = "Nintendont"
score1 = 3
team2 = "Funny Fauna"
score2 = 5

#12
[[brackets.losers]]
team1 = "Autoism"
score1 = 3
team2 = "Moai"
score2 = 2

#17
[[brackets.losers]]
team1 = "Legoland"
score1 = 2
team2 = "FC Fine Dining"
score2 = 0

#18
[[brackets.losers]]
team1 = "Bone Zone"
score1 = 2
team2 = "Vidya"
score2 = 1

#19
[[brackets.losers]]
team1 = "Gambit"
score1 = 1
team2 = "Funny Fauna"
score2 = 3

#20
[[brackets.losers]]
team1 = "Cartoons FC"
score1 = 3
team2 = "Autoism"
score2 = 2

#23
[[brackets.losers]]
team1 = "Legoland"
score1 = 3
team2 = "Bone Zone"
score2 = 2


#24
[[brackets.losers]]
team1 = "Funny Fauna"
score1 = 1
team2 = "Cartoons FC"
score2 = 2

#25
[[brackets.losers]]
team1 = "Cursed"
score1 = 1
pen1 = 3
team2 = "Legoland"
score2 = 1
pen2 = 4

#26
[[brackets.losers]]
team1 = "Big Funky"
score1 = 1
team2 = "Cartoons FC"
score2 = 2

#28
[[brackets.losers]]
team1 = "Legoland"
score1 = 2
team2 = "Cartoons FC"
score2 = 3

#29
[[brackets.losers]]
team1 = "Alpha Space Bros"
score1 = 0
team2 = "Cartoons FC"
score2 = 3
